# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'weibo' do
pod 'SDAutoLayout', '2.2.1'
pod 'AFNetworking', '~>4.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weibo

end
